In [18]:
import pandas as pd
import numpy as np
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score
from imblearn.over_sampling import RandomOverSampler
from imblearn.under_sampling import RandomUnderSampler
from sklearn.preprocessing import StandardScaler
import pickle

In [3]:
df=pd.read_csv('creditcard.csv')

In [4]:
# to see all the columns in dataset

pd.options.display.max_columns=None

In [5]:
df.head()

Time        V1        V2        V3        V4        V5        V6        V7  \
0   0.0 -1.359807 -0.072781  2.536347  1.378155 -0.338321  0.462388  0.239599   
1   0.0  1.191857  0.266151  0.166480  0.448154  0.060018 -0.082361 -0.078803   
2   1.0 -1.358354 -1.340163  1.773209  0.379780 -0.503198  1.800499  0.791461   
3   1.0 -0.966272 -0.185226  1.792993 -0.863291 -0.010309  1.247203  0.237609   
4   2.0 -1.158233  0.877737  1.548718  0.403034 -0.407193  0.095921  0.592941   

         V8        V9       V10       V11       V12       V13       V14  \
0  0.098698  0.363787  0.090794 -0.551600 -0.617801 -0.991390 -0.311169   
1  0.085102 -0.255425 -0.166974  1.612727  1.065235  0.489095 -0.143772   
2  0.247676 -1.514654  0.207643  0.624501  0.066084  0.717293 -0.165946   
3  0.377436 -1.387024 -0.054952 -0.226487  0.178228  0.507757 -0.287924   
4 -0.270533  0.817739  0.753074 -0.822843  0.538196  1.345852 -1.119670   

        V15       V16       V17       V18       V19       V20       V21  \
0  1.468177 -0.470401  0.207971  0.025791  0.403993  0.251412 -0.018307   
1  0.635558  0.463917 -0.114805 -0.183361 -0.145783 -0.069083 -0.225775   
2  2.345865 -2.890083  1.109969 -0.121359 -2.261857  0.524980  0.247998   
3 -0.631418 -1.059647 -0.684093  1.965775 -1.232622 -0.208038 -0.108300   
4  0.175121 -0.451449 -0.237033 -0.038195  0.803487  0.408542 -0.009431   

        V22       V23       V24       V25       V26       V27       V28  \
0  0.277838 -0.110474  0.066928  0.128539 -0.189115  0.133558 -0.021053   
1 -0.638672  0.101288 -0.339846  0.167170  0.125895 -0.008983  0.014724   
2  0.771679  0.909412 -0.689281 -0.327642 -0.139097 -0.055353 -0.059752   
3  0.005274 -0.190321 -1.175575  0.647376 -0.221929  0.062723  0.061458   
4  0.798278 -0.137458  0.141267 -0.206010  0.502292  0.219422  0.215153   

   Amount  Class  
0  149.62      0  
1    2.69      0  
2  378.66      0  
3  123.50      0  
4   69.99      0

# data Preprocessing


In [6]:
df['Class'].value_counts()

# this is an imbalance data we have to apply undersampling or oversampling to balance it

Class
0    284315
1       492
Name: count, dtype: int64

In [7]:
# we are going to standardize the amount column so that it can scale with other columns
ss =  StandardScaler()
df['Amount']=ss.fit_transform(df[['Amount']])

In [8]:
df.head()

Time        V1        V2        V3        V4        V5        V6        V7  \
0   0.0 -1.359807 -0.072781  2.536347  1.378155 -0.338321  0.462388  0.239599   
1   0.0  1.191857  0.266151  0.166480  0.448154  0.060018 -0.082361 -0.078803   
2   1.0 -1.358354 -1.340163  1.773209  0.379780 -0.503198  1.800499  0.791461   
3   1.0 -0.966272 -0.185226  1.792993 -0.863291 -0.010309  1.247203  0.237609   
4   2.0 -1.158233  0.877737  1.548718  0.403034 -0.407193  0.095921  0.592941   

         V8        V9       V10       V11       V12       V13       V14  \
0  0.098698  0.363787  0.090794 -0.551600 -0.617801 -0.991390 -0.311169   
1  0.085102 -0.255425 -0.166974  1.612727  1.065235  0.489095 -0.143772   
2  0.247676 -1.514654  0.207643  0.624501  0.066084  0.717293 -0.165946   
3  0.377436 -1.387024 -0.054952 -0.226487  0.178228  0.507757 -0.287924   
4 -0.270533  0.817739  0.753074 -0.822843  0.538196  1.345852 -1.119670   

        V15       V16       V17       V18       V19       V20       V21  \
0  1.468177 -0.470401  0.207971  0.025791  0.403993  0.251412 -0.018307   
1  0.635558  0.463917 -0.114805 -0.183361 -0.145783 -0.069083 -0.225775   
2  2.345865 -2.890083  1.109969 -0.121359 -2.261857  0.524980  0.247998   
3 -0.631418 -1.059647 -0.684093  1.965775 -1.232622 -0.208038 -0.108300   
4  0.175121 -0.451449 -0.237033 -0.038195  0.803487  0.408542 -0.009431   

        V22       V23       V24       V25       V26       V27       V28  \
0  0.277838 -0.110474  0.066928  0.128539 -0.189115  0.133558 -0.021053   
1 -0.638672  0.101288 -0.339846  0.167170  0.125895 -0.008983  0.014724   
2  0.771679  0.909412 -0.689281 -0.327642 -0.139097 -0.055353 -0.059752   
3  0.005274 -0.190321 -1.175575  0.647376 -0.221929  0.062723  0.061458   
4  0.798278 -0.137458  0.141267 -0.206010  0.502292  0.219422  0.215153   

     Amount  Class  
0  0.244964      0  
1 -0.342475      0  
2  1.160686      0  
3  0.140534      0  
4 -0.073403      0

In [9]:
df.describe()

Time            V1            V2            V3            V4  \
count  284807.000000  2.848070e+05  2.848070e+05  2.848070e+05  2.848070e+05   
mean    94813.859575  1.168375e-15  3.416908e-16 -1.379537e-15  2.074095e-15   
std     47488.145955  1.958696e+00  1.651309e+00  1.516255e+00  1.415869e+00   
min         0.000000 -5.640751e+01 -7.271573e+01 -4.832559e+01 -5.683171e+00   
25%     54201.500000 -9.203734e-01 -5.985499e-01 -8.903648e-01 -8.486401e-01   
50%     84692.000000  1.810880e-02  6.548556e-02  1.798463e-01 -1.984653e-02   
75%    139320.500000  1.315642e+00  8.037239e-01  1.027196e+00  7.433413e-01   
max    172792.000000  2.454930e+00  2.205773e+01  9.382558e+00  1.687534e+01   

                 V5            V6            V7            V8            V9  \
count  2.848070e+05  2.848070e+05  2.848070e+05  2.848070e+05  2.848070e+05   
mean   9.604066e-16  1.487313e-15 -5.556467e-16  1.213481e-16 -2.406331e-15   
std    1.380247e+00  1.332271e+00  1.237094e+00  1.194353e+00  1.098632e+00   
min   -1.137433e+02 -2.616051e+01 -4.355724e+01 -7.321672e+01 -1.343407e+01   
25%   -6.915971e-01 -7.682956e-01 -5.540759e-01 -2.086297e-01 -6.430976e-01   
50%   -5.433583e-02 -2.741871e-01  4.010308e-02  2.235804e-02 -5.142873e-02   
75%    6.119264e-01  3.985649e-01  5.704361e-01  3.273459e-01  5.971390e-01   
max    3.480167e+01  7.330163e+01  1.205895e+02  2.000721e+01  1.559499e+01   

                V10           V11           V12           V13           V14  \
count  2.848070e+05  2.848070e+05  2.848070e+05  2.848070e+05  2.848070e+05   
mean   2.239053e-15  1.673327e-15 -1.247012e-15  8.190001e-16  1.207294e-15   
std    1.088850e+00  1.020713e+00  9.992014e-01  9.952742e-01  9.585956e-01   
min   -2.458826e+01 -4.797473e+00 -1.868371e+01 -5.791881e+00 -1.921433e+01   
25%   -5.354257e-01 -7.624942e-01 -4.055715e-01 -6.485393e-01 -4.255740e-01   
50%   -9.291738e-02 -3.275735e-02  1.400326e-01 -1.356806e-02  5.060132e-02   
75%    4.539234e-01  7.395934e-01  6.182380e-01  6.625050e-01  4.931498e-01   
max    2.374514e+01  1.201891e+01  7.848392e+00  7.126883e+00  1.052677e+01   

                V15           V16           V17           V18           V19  \
count  2.848070e+05  2.848070e+05  2.848070e+05  2.848070e+05  2.848070e+05   
mean   4.887456e-15  1.437716e-15 -3.772171e-16  9.564149e-16  1.039917e-15   
std    9.153160e-01  8.762529e-01  8.493371e-01  8.381762e-01  8.140405e-01   
min   -4.498945e+00 -1.412985e+01 -2.516280e+01 -9.498746e+00 -7.213527e+00   
25%   -5.828843e-01 -4.680368e-01 -4.837483e-01 -4.988498e-01 -4.562989e-01   
50%    4.807155e-02  6.641332e-02 -6.567575e-02 -3.636312e-03  3.734823e-03   
75%    6.488208e-01  5.232963e-01  3.996750e-01  5.008067e-01  4.589494e-01   
max    8.877742e+00  1.731511e+01  9.253526e+00  5.041069e+00  5.591971e+00   

                V20           V21           V22           V23           V24  \
count  2.848070e+05  2.848070e+05  2.848070e+05  2.848070e+05  2.848070e+05   
mean   6.406204e-16  1.654067e-16 -3.568593e-16  2.578648e-16  4.473266e-15   
std    7.709250e-01  7.345240e-01  7.257016e-01  6.244603e-01  6.056471e-01   
min   -5.449772e+01 -3.483038e+01 -1.093314e+01 -4.480774e+01 -2.836627e+00   
25%   -2.117214e-01 -2.283949e-01 -5.423504e-01 -1.618463e-01 -3.545861e-01   
50%   -6.248109e-02 -2.945017e-02  6.781943e-03 -1.119293e-02  4.097606e-02   
75%    1.330408e-01  1.863772e-01  5.285536e-01  1.476421e-01  4.395266e-01   
max    3.942090e+01  2.720284e+01  1.050309e+01  2.252841e+01  4.584549e+00   

                V25           V26           V27           V28        Amount  \
count  2.848070e+05  2.848070e+05  2.848070e+05  2.848070e+05  2.848070e+05   
mean   5.340915e-16  1.683437e-15 -3.660091e-16 -1.227390e-16  2.913952e-17   
std    5.212781e-01  4.822270e-01  4.036325e-01  3.300833e-01  1.000002e+00   
min   -1.029540e+01 -2.604551e+00 -2.256568e+01 -1.543008e+01 -3.532294e-01   
25%   -3.171451e-01 -3.269839e-01 -7.083953e-02 -5.2

In [10]:
df.shape

(284807, 31)

In [11]:
x=df.drop(['Class','Time'],axis=1)
y=df['Class']

# Over Sampling

In [12]:
ros = RandomOverSampler(random_state=2, sampling_strategy='auto')

In [13]:
x_ros,y_ros=ros.fit_resample(x,y)
y_ros.value_counts()

Class
0    284315
1    284315
Name: count, dtype: int64

In [66]:
x_train,x_test,y_train,y_test = train_test_split(x_ros,y_ros,test_size=0.3)

In [16]:
models = {
    'decision Tree': DecisionTreeClassifier(),
    'Logistic Regression': LogisticRegression()
}

for model_name, model in models.items():
    print(f'\n================ {model_name} ======================\n')
    model.fit(x_train,y_train)
    y_pred=model.predict(x_test)
    print(f'Accuracy Score: {accuracy_score(y_pred,y_test)}')
    print(f'Precision: {precision_score(y_pred,y_test)}')
    print(f'f1 Score: {f1_score(y_pred,y_test)}')
    print(f'recall Score: {recall_score(y_pred,y_test)}')


================ decision Tree ======================

Accuracy Score: 0.9997303460363799
Precision: 1.0
f1 Score: 0.9997296884365414
recall Score: 0.9994595229702737

================ Logistic Regression ======================

Accuracy Score: 0.9493578132235959
Precision: 0.9218470798457632
f1 Score: 0.9477914559046601
recall Score: 0.9752384742621911


In [17]:
# picking the decision tree model

dtc = DecisionTreeClassifier()
dtc.fit(x_train,y_train)

DecisionTreeClassifier()

In [19]:
pickle.dump(dtc,open('dtc_model.pkl','wb'))

In [20]:
pickle.dump(ss,open('StandardScaler.pkl','wb'))

# Under Sampling

In [21]:
rus = RandomUnderSampler(random_state=2, sampling_strategy='majority')

In [25]:
x_rus,y_rus=rus.fit_resample(x,y)
y_rus.value_counts()

Class
0    492
1    492
Name: count, dtype: int64

In [26]:
x_train,x_test,y_train,y_test = train_test_split(x_rus,y_rus,test_size=0.3)

In [27]:
models = {
    'decision Tree': DecisionTreeClassifier(),
    'Logistic Regression': LogisticRegression()
}

for model_name, model in models.items():
    print(f'\n================ {model_name} ======================\n')
    model.fit(x_train,y_train)
    y_pred=model.predict(x_test)
    print(f'Accuracy Score: {accuracy_score(y_pred,y_test)}')
    print(f'Precision: {precision_score(y_pred,y_test)}')
    print(f'f1 Score: {f1_score(y_pred,y_test)}')
    print(f'recall Score: {recall_score(y_pred,y_test)}')


================ decision Tree ======================

Accuracy Score: 0.8986486486486487
Precision: 0.922077922077922
f1 Score: 0.9044585987261146
recall Score: 0.8875

================ Logistic Regression ======================

Accuracy Score: 0.9527027027027027
Precision: 0.9285714285714286
f1 Score: 0.9533333333333334
recall Score: 0.9794520547945206


In [28]:
# Over sampling work instead of under sampling so we will go with over sampling

In [64]:
dtc.predict(x_ros.iloc[20080].values.reshape(1,-1))

C:\Users\shani\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(


array([0], dtype=int64)

In [41]:
np.array([-1.3598071336738,-0.0727811733098497,2.53634673796914,1.37815522427443,-0.338320769942518,0.462387777762292,0.239598554061257,0.0986979012610507,0.363786969611213,0.0907941719789316,-0.551599533260813,-0.617800855762348,-0.991389847235408,-0.311169353699879,1.46817697209427,-0.470400525259478,0.207971241929242,0.0257905801985591,0.403992960255733,0.251412098239705,-0.018306777944153,0.277837575558899,-0.110473910188767,0.0669280749146731,0.128539358273528,-0.189114843888824,0.133558376740387,-0.0210530534538215,149.62]).reshape(1,-1)

array([[-1.35980713e+00, -7.27811733e-02,  2.53634674e+00,
         1.37815522e+00, -3.38320770e-01,  4.62387778e-01,
         2.39598554e-01,  9.86979013e-02,  3.63786970e-01,
         9.07941720e-02, -5.51599533e-01, -6.17800856e-01,
        -9.91389847e-01, -3.11169354e-01,  1.46817697e+00,
        -4.70400525e-01,  2.07971242e-01,  2.57905802e-02,
         4.03992960e-01,  2.51412098e-01, -1.83067779e-02,
         2.77837576e-01, -1.10473910e-01,  6.69280749e-02,
         1.28539358e-01, -1.89114844e-01,  1.33558377e-01,
        -2.10530535e-02,  1.49620000e+02]])

In [45]:
df.drop(['Time','Class'],axis=1).iloc[0].values

array([-1.35980713, -0.07278117,  2.53634674,  1.37815522, -0.33832077,
        0.46238778,  0.23959855,  0.0986979 ,  0.36378697,  0.09079417,
       -0.55159953, -0.61780086, -0.99138985, -0.31116935,  1.46817697,
       -0.47040053,  0.20797124,  0.02579058,  0.40399296,  0.2514121 ,
       -0.01830678,  0.27783758, -0.11047391,  0.06692807,  0.12853936,
       -0.18911484,  0.13355838, -0.02105305,  0.24496426])

In [65]:
y_ros.value_counts()

Class
0    284315
1    284315
Name: count, dtype: int64

Class
0    284315
1       492
Name: count, dtype: int64